# Optional configs used by Nextstrain team
# Params for uploads
upload:
  # Upload params for AWS S3
  s3:
    # AWS S3 Bucket with prefix
    dst: 's3://nextstrain-data/files/workflows/mpox'
    # Mapping of files to upload, with key as remote file name and the value
    # the local file path relative to the ingest/data directory.
    files_to_upload:
      genbank.ndjson.xz: genbank.ndjson
      all_sequences.ndjson.xz: sequences.ndjson
      metadata.tsv.gz: metadata.tsv
      sequences.fasta.xz: sequences.fasta
      alignment.fasta.xz: alignment.fasta
      insertions.csv.gz: insertions.csv
      translations.zip: translations.zip

    cloudfront_domain: 'data.nextstrain.org'

# Toggle for Slack notifications
send_slack_notifications: True

# Toggle for triggering builds
trigger_rebuild: True
