colors: "config/colors_hmpxv1.tsv"
auspice_config: "config/auspice_config_hmpxv1_big.json"

build_name: "hmpxv1_big"
auspice_name: "monkeypox_hmpxv1_big"

## filter
min_date: 2017
min_length: 100000
sequences_per_group: ""
group_by: ""
filters: "--exclude-where outbreak!=hMPXV-1"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"
