colors: "config/colors_mpxv.tsv"
auspice_config: "config/auspice_config_mpxv.json"

build_name: "mpxv"
auspice_name: "monkeypox_mpxv"

## filter
min_date: 1950
min_length: 100000
group_by: "--group-by clade year country"
sequences_per_group: "--sequences-per-group 50"

## refine
timetree: false
root: "min_dev"
clock_rate: 3e-6
clock_std_dev: 6e-6

mask:
  from_beginning: 1350
  from_end: 6422
  maskfile: "config/mask_overview.bed"
