exclude: "config/exclude.txt"
include: "config/include.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config.json"
description: "config/description.md"

## filter
min_date: 2020
min_length: 10000

## align
max_indel: 5000
seed_spacing: 1000

## refine
root: "MPXV-UK_P2"
divergence_unit: 'mutations'

mask:
  from_beginning: 7000
  from_end: 7000
  maskfile: "config/mask.bed"
