name: Rebuild mpxv

on:
  repository_dispatch:
    types:
      - rebuild
      - rebuild_mpxv

  workflow_dispatch:
    inputs:
      image:
        description: 'Specific container image to use for build (will override the default of "nextstrain build")'
        required: false

env:
  NEXTSTRAIN_DOCKER_IMAGE: ${{ github.event.inputs.image }}

jobs:
  rebuild_mpxv:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      SLACK_CHANNELS: monkeypox-updates
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
      with:
        cli-version: ">=7.1.0"
        python-version: "3.10"

    - name: launch_build
      run: |
        nextstrain build \
          --aws-batch \
          --detach \
          --no-download \
          --cpus 8 \
          --memory 32gib \
          --env AWS_DEFAULT_REGION \
          --env AWS_ACCESS_KEY_ID \
          --env AWS_SECRET_ACCESS_KEY \
          --env GITHUB_RUN_ID \
          --env SLACK_TOKEN \
          --env SLACK_CHANNELS \
          . \
            notify_on_deploy \
              --configfiles config/config_mpxv.yaml config/nextstrain_automation.yaml
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: notify_pipeline_failed
      if: ${{ failure() }}
      run: ./bin/notify-on-error

