name: Rebuild all

on:
  workflow_dispatch:

jobs:
  rebuild_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Repository Dispatch
        run: ./ingest/bin/trigger monkeypox rebuild
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          SLACK_CHANNELS: monkeypox-updates
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PAT_GITHUB_DISPATCH: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_WORKFLOW_DISPATCH }}
